version: '3'
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile-web
    depends_on:
      - rabbitmq
      - mongo
      - server
    ports:
      - "5000:5000"
    volumes:
      - .:/code
  twitter:
     build:
        context: .
        dockerfile: Dockerfile-twitter
     depends_on:
      - rabbitmq
      - mongo
      - server
  server:
     build:
        context: .
        dockerfile: Dockerfile-server
     depends_on:
      - rabbitmq
      - mongo
  mongo:
    image: mongo:3.0.2
  rabbitmq:
    image: rabbitmq:3.6.1-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "8023:15672"
      - "8024:5672"